// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEYF-E1NUgMj6Qkl2C5Cq8vLH7qUIOnHI',
    appId: '1:142510548925:web:8a8557108b47bfe51494d4',
    messagingSenderId: '142510548925',
    projectId: 'demo3-login',
    authDomain: 'demo3-login.firebaseapp.com',
    storageBucket: 'demo3-login.appspot.com',
    measurementId: 'G-48GVLXS647',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_e-T5kaaPUuxqZXUaYk2j65oZ8FUA2c',
    appId: '1:142510548925:android:fc9d3202ef726b761494d4',
    messagingSenderId: '142510548925',
    projectId: 'demo3-login',
    storageBucket: 'demo3-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDydxcvcFiDpXR6nhHYQ1B9w0ek4YFcmmI',
    appId: '1:142510548925:ios:5ecdfaed3cb3b8cd1494d4',
    messagingSenderId: '142510548925',
    projectId: 'demo3-login',
    storageBucket: 'demo3-login.appspot.com',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDydxcvcFiDpXR6nhHYQ1B9w0ek4YFcmmI',
    appId: '1:142510548925:ios:70cb8c0124b3ecab1494d4',
    messagingSenderId: '142510548925',
    projectId: 'demo3-login',
    storageBucket: 'demo3-login.appspot.com',
    iosBundleId: 'com.example.demo3.RunnerTests',
  );
}
